services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=supersecret
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI port
    networks:
      - mq-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5 

  app:
    build: .
    container_name: python-app
    environment:
      - BROKER_URL=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - mq-network

networks:
  mq-network:
    driver: bridge

volumes:
  rabbit_data:



