services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    hostname: rabbit-server
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI port
    networks:
      - mq-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5 
    environment:
      # FIXED: Using the correct internal RabbitMQ variable names
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=supersecret
      - RABBITMQ_NODENAME=rabbit@rabbitmq
    volumes:
      - rabbit_data:/var/lib/rabbitmq
  app:
    build: .
    # container_name: python-app
    environment:
      - BROKER_URL=rabbitmq
      - RABBIT_USER=admin
      - RABBIT_PASS=supersecret
    depends_on:
      - rabbitmq
    networks:
      - mq-network

networks:
  mq-network:
    driver: bridge

volumes:
  rabbit_data:


